apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    some-label: some-label-value
  namespace: jenkins
spec:
  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true